pipeline {
    agent any
    stages {
        stageb ("build") {
            steps {
                echo "building my app..."
            }
        }
        stage ("test") {
            steps {
                echo "testing my app..."
            }
        }
        stage ("deploy") {
            steps {
                echo "deploying my app..."
            }
        }
    }
}